package org.example.dao;

import org.example.dataobject.UserAvatarDO;

public interface UserAvatarDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_avatar
     *
     * @mbg.generated Fri Apr 15 09:22:41 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    int deleteByUserId(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_avatar
     *
     * @mbg.generated Fri Apr 15 09:22:41 CST 2022
     */
    int insert(UserAvatarDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_avatar
     *
     * @mbg.generated Fri Apr 15 09:22:41 CST 2022
     */
    int insertSelective(UserAvatarDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_avatar
     *
     * @mbg.generated Fri Apr 15 09:22:41 CST 2022
     */
    UserAvatarDO selectByPrimaryKey(Integer id);

    String selectHeadUrlByUserId(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_avatar
     *
     * @mbg.generated Fri Apr 15 09:22:41 CST 2022
     */
    int updateByPrimaryKeySelective(UserAvatarDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_avatar
     *
     * @mbg.generated Fri Apr 15 09:22:41 CST 2022
     */
    int updateByPrimaryKey(UserAvatarDO record);
}