package org.example.dao;

import org.apache.catalina.User;
import org.example.dataobject.UserDO;
import org.example.service.model.UserModel;
import org.springframework.stereotype.Repository;

@Repository
public interface UserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Mar 07 20:25:44 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Mar 07 20:25:44 CST 2022
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Mar 07 20:25:44 CST 2022
     */
    int insertSelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Mar 07 20:25:44 CST 2022
     */
    UserDO selectByPrimaryKey(Integer id);

    UserDO selectByTelephone(String telephone);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Mar 07 20:25:44 CST 2022
     */
    int updateByPrimaryKeySelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Mar 07 20:25:44 CST 2022
     */
    int updateByPrimaryKey(UserDO record);

    int updateNameByTelephone(UserDO record);

    int updateGenderByTelephone(UserDO record);

    int updateAgeByTelephone(UserDO userDO);
}