package org.example.dataobject;

import java.math.BigDecimal;
import java.util.Date;

public class LocationTagsDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location_tags.loc_id
     *
     * @mbg.generated Thu May 05 19:09:23 CST 2022
     */
    private Integer locId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location_tags.longitude
     *
     * @mbg.generated Thu May 05 19:09:23 CST 2022
     */
    private BigDecimal longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location_tags.latitude
     *
     * @mbg.generated Thu May 05 19:09:23 CST 2022
     */
    private BigDecimal latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location_tags.location_desc
     *
     * @mbg.generated Thu May 05 19:09:23 CST 2022
     */
    private String locationDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location_tags.location_tag
     *
     * @mbg.generated Thu May 05 19:09:23 CST 2022
     */
    private String locationTag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location_tags.location_radius
     *
     * @mbg.generated Thu May 05 19:09:23 CST 2022
     */
    private Integer locationRadius;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location_tags.loc_id
     *
     * @return the value of location_tags.loc_id
     *
     * @mbg.generated Thu May 05 19:09:23 CST 2022
     */
    public Integer getLocId() {
        return locId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location_tags.loc_id
     *
     * @param locId the value for location_tags.loc_id
     *
     * @mbg.generated Thu May 05 19:09:23 CST 2022
     */
    public void setLocId(Integer locId) {
        this.locId = locId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location_tags.longitude
     *
     * @return the value of location_tags.longitude
     *
     * @mbg.generated Thu May 05 19:09:23 CST 2022
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location_tags.longitude
     *
     * @param longitude the value for location_tags.longitude
     *
     * @mbg.generated Thu May 05 19:09:23 CST 2022
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location_tags.latitude
     *
     * @return the value of location_tags.latitude
     *
     * @mbg.generated Thu May 05 19:09:23 CST 2022
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location_tags.latitude
     *
     * @param latitude the value for location_tags.latitude
     *
     * @mbg.generated Thu May 05 19:09:23 CST 2022
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location_tags.location_desc
     *
     * @return the value of location_tags.location_desc
     *
     * @mbg.generated Thu May 05 19:09:23 CST 2022
     */
    public String getLocationDesc() {
        return locationDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location_tags.location_desc
     *
     * @param locationDesc the value for location_tags.location_desc
     *
     * @mbg.generated Thu May 05 19:09:23 CST 2022
     */
    public void setLocationDesc(String locationDesc) {
        this.locationDesc = locationDesc == null ? null : locationDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location_tags.location_tag
     *
     * @return the value of location_tags.location_tag
     *
     * @mbg.generated Thu May 05 19:09:23 CST 2022
     */
    public String getLocationTag() {
        return locationTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location_tags.location_tag
     *
     * @param locationTag the value for location_tags.location_tag
     *
     * @mbg.generated Thu May 05 19:09:23 CST 2022
     */
    public void setLocationTag(String locationTag) {
        this.locationTag = locationTag == null ? null : locationTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location_tags.location_radius
     *
     * @return the value of location_tags.location_radius
     *
     * @mbg.generated Thu May 05 19:09:23 CST 2022
     */
    public Integer getLocationRadius() {
        return locationRadius;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location_tags.location_radius
     *
     * @param locationRadius the value for location_tags.location_radius
     *
     * @mbg.generated Thu May 05 19:09:23 CST 2022
     */
    public void setLocationRadius(Integer locationRadius) {
        this.locationRadius = locationRadius;
    }

}