package org.example.dataobject;

public class TempDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.temp_id
     *
     * @mbg.generated Sun May 08 08:58:16 CST 2022
     */
    private Integer tempId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.user_tel
     *
     * @mbg.generated Sun May 08 08:58:16 CST 2022
     */
    private String userTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.cur_time
     *
     * @mbg.generated Sun May 08 08:58:16 CST 2022
     */
    private Long curTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.loc_describe
     *
     * @mbg.generated Sun May 08 08:58:16 CST 2022
     */
    private String locDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.tag
     *
     * @mbg.generated Sun May 08 08:58:16 CST 2022
     */
    private String tag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.temp_id
     *
     * @return the value of temp.temp_id
     *
     * @mbg.generated Sun May 08 08:58:16 CST 2022
     */
    public Integer getTempId() {
        return tempId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.temp_id
     *
     * @param tempId the value for temp.temp_id
     *
     * @mbg.generated Sun May 08 08:58:16 CST 2022
     */
    public void setTempId(Integer tempId) {
        this.tempId = tempId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.user_tel
     *
     * @return the value of temp.user_tel
     *
     * @mbg.generated Sun May 08 08:58:16 CST 2022
     */
    public String getUserTel() {
        return userTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.user_tel
     *
     * @param userTel the value for temp.user_tel
     *
     * @mbg.generated Sun May 08 08:58:16 CST 2022
     */
    public void setUserTel(String userTel) {
        this.userTel = userTel == null ? null : userTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.cur_time
     *
     * @return the value of temp.cur_time
     *
     * @mbg.generated Sun May 08 08:58:16 CST 2022
     */
    public Long getCurTime() {
        return curTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.cur_time
     *
     * @param curTime the value for temp.cur_time
     *
     * @mbg.generated Sun May 08 08:58:16 CST 2022
     */
    public void setCurTime(Long curTime) {
        this.curTime = curTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.loc_describe
     *
     * @return the value of temp.loc_describe
     *
     * @mbg.generated Sun May 08 08:58:16 CST 2022
     */
    public String getLocDescribe() {
        return locDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.loc_describe
     *
     * @param locDescribe the value for temp.loc_describe
     *
     * @mbg.generated Sun May 08 08:58:16 CST 2022
     */
    public void setLocDescribe(String locDescribe) {
        this.locDescribe = locDescribe == null ? null : locDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.tag
     *
     * @return the value of temp.tag
     *
     * @mbg.generated Sun May 08 08:58:16 CST 2022
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.tag
     *
     * @param tag the value for temp.tag
     *
     * @mbg.generated Sun May 08 08:58:16 CST 2022
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

}