package org.example.dataobject;

import java.math.BigDecimal;
import java.util.Date;

public class UserScheduleDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_schedule.id
     *
     * @mbg.generated Sat Apr 02 11:10:08 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_schedule.longitude
     *
     * @mbg.generated Sat Apr 02 11:10:08 CST 2022
     */
    private BigDecimal longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_schedule.latitude
     *
     * @mbg.generated Sat Apr 02 11:10:08 CST 2022
     */
    private BigDecimal latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_schedule.user_id
     *
     * @mbg.generated Sat Apr 02 11:10:08 CST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_schedule.schedule_title
     *
     * @mbg.generated Sat Apr 02 11:10:08 CST 2022
     */
    private String scheduleTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_schedule.schedule_info
     *
     * @mbg.generated Sat Apr 02 11:10:08 CST 2022
     */
    private String scheduleInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_schedule.schedule_start_time
     *
     * @mbg.generated Sat Apr 02 11:10:08 CST 2022
     */
    private Long scheduleStartTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_schedule.id
     *
     * @return the value of user_schedule.id
     *
     * @mbg.generated Sat Apr 02 11:10:08 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_schedule.id
     *
     * @param id the value for user_schedule.id
     *
     * @mbg.generated Sat Apr 02 11:10:08 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_schedule.longitude
     *
     * @return the value of user_schedule.longitude
     *
     * @mbg.generated Sat Apr 02 11:10:08 CST 2022
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_schedule.longitude
     *
     * @param longitude the value for user_schedule.longitude
     *
     * @mbg.generated Sat Apr 02 11:10:08 CST 2022
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_schedule.latitude
     *
     * @return the value of user_schedule.latitude
     *
     * @mbg.generated Sat Apr 02 11:10:08 CST 2022
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_schedule.latitude
     *
     * @param latitude the value for user_schedule.latitude
     *
     * @mbg.generated Sat Apr 02 11:10:08 CST 2022
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_schedule.user_id
     *
     * @return the value of user_schedule.user_id
     *
     * @mbg.generated Sat Apr 02 11:10:08 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_schedule.user_id
     *
     * @param userId the value for user_schedule.user_id
     *
     * @mbg.generated Sat Apr 02 11:10:08 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_schedule.schedule_title
     *
     * @return the value of user_schedule.schedule_title
     *
     * @mbg.generated Sat Apr 02 11:10:08 CST 2022
     */
    public String getScheduleTitle() {
        return scheduleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_schedule.schedule_title
     *
     * @param scheduleTitle the value for user_schedule.schedule_title
     *
     * @mbg.generated Sat Apr 02 11:10:08 CST 2022
     */
    public void setScheduleTitle(String scheduleTitle) {
        this.scheduleTitle = scheduleTitle == null ? null : scheduleTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_schedule.schedule_info
     *
     * @return the value of user_schedule.schedule_info
     *
     * @mbg.generated Sat Apr 02 11:10:08 CST 2022
     */
    public String getScheduleInfo() {
        return scheduleInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_schedule.schedule_info
     *
     * @param scheduleInfo the value for user_schedule.schedule_info
     *
     * @mbg.generated Sat Apr 02 11:10:08 CST 2022
     */
    public void setScheduleInfo(String scheduleInfo) {
        this.scheduleInfo = scheduleInfo == null ? null : scheduleInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_schedule.schedule_start_time
     *
     * @return the value of user_schedule.schedule_start_time
     *
     * @mbg.generated Sat Apr 02 11:10:08 CST 2022
     */
    public Long getScheduleStartTime() {
        return scheduleStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_schedule.schedule_start_time
     *
     * @param scheduleStartTime the value for user_schedule.schedule_start_time
     *
     * @mbg.generated Sat Apr 02 11:10:08 CST 2022
     */
    public void setScheduleStartTime(Long scheduleStartTime) {
        this.scheduleStartTime = scheduleStartTime;
    }

}